---
title: Online Resources I Really Like
author: TF
date: "`r Sys.Date()`"
slug: online-resources-i-really-like
categories: []
tags: []
subtitle: ''
summary: 'These are online resources that great information and educational value'
authors: []
lastmod: "`r Sys.Date()`"
featured: yes
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

Online Resources I Find Helpful
---
Title and Author | Description and/or Extra Material
---|----
[**Introduction to Modern Causal Inference**](https://alejandroschuler.github.io/mci/)|by Alejandro Schuler. Such a fantastic general introduction to casual thinking from a more technical viewpoint. It is a work in progress|
[**Statistics Notes in the BMJ**](https://www-users.york.ac.uk/~mb55/pubs/pbstnote.htm)|An online repository of all the Statistics notes published in the BMJ by Martin Bland and the late Doug Altman. What a treasure trove.|
[**Notes and resources by David Freedman**](https://www.stat.berkeley.edu/~freedman/)|Page with links to many of the late David Freedman's notes and papers, which are quite high quality.|
[**Improving Your Statistical Inferences**](https://lakens.github.io/statistical_inferences/)|by Daniel Lakens. Its a great resource for understanding more about epistemology and how it relates to statistical inference. It is a work in progress, but has exercises and is reasonably regularly updated|
[**The Harrell-verse**](https://hbiostat.org/)| The Frank Harrell Jr. universe for stats education. Included gems like [Biostatistic for Biomedical Researchers](https://hbiostat.org/bbr/), links to his frequented sites, rec'd blogs, etc.|
[**Interactive Linear Algebra Book**](https://textbooks.math.gatech.edu/ila/index.html) [**Understanding Linear Algebra**](https://understandinglinearalgebra.org/preface-1.html) and [**Immersive Linear Algebra**](http://immersivemath.com/ila/index.html)| Interested in learning linear algebra? Want to have an interactive textbook the allow manipulation of 3-d objects? These are the best resources I've found.|
[**Linear Algebra for Data Science**](https://shainarace.github.io/LinearAlgebra/index.html)| By a UNC graduate in Stat and Operations Research, Shaina Race Bennett. It's a fantastic introduction to linear algebra and the immediate relevance for statistics.|
[**Math Basics**](https://tutorial.math.lamar.edu/)|Online Calc 1-3 and differential equations textbook with review of algebra and trig. Nice because it is fairly in depth and included proofs (where other books fail)|
[**R-Universe**](https://r-universe.dev/search/)|Searchable database of R packages. Nice and visually appealing, and nice to search than CRAN|
[**Draw Data**](https://drawdata.xyz/)|Have data in mind, and want a dataset to exist with data in a specific pattern? Well here you can draw the pattern and output a dataset to correspond with that pattern.|
[**UNC Causal Inference Research Group**](https://causal.unc.edu/)|The research group of which I am a member. Has monthly talks.|
[**Epidemiolog.net**](http://www.epidemiolog.net/)|Victor Schoenbach's page of resources. Vic was a professor of epidemiology at UNC for many years, and this is also a treasure trove of material.|
[**R Pscyhologist**](http://www.epidemiolog.net/)| Visualizations of many statistical phenomena with interactive shiny based widgets. Great for education|
[**SticiGui**](https://www.stat.berkeley.edu/~stark/SticiGui/index.htm)| Online statistics textbook by Philip Stark at Berkeley. I really enjoy that it covers a first course in stats, but also included logic and set theory instead of glossing over that.|
Stephen Senn's [**Blog Post list**](http://www.senns.uk/Blogs.html) and [**Statistics Notes**](http://www.senns.uk/Stats_notes.html)|Stephen Senn is a exceptionally accomplished statistician. This is his own collated list of things he has written about that is available on the internet. Highly recommended|
[**The Effect**](https://theeffectbook.net/index.html)|Nick Huntington Klein's The Effet book available free online. If you like it I strongly suggest supporting the author by purchasing a copy|
[**DAGs from Hernan and Robins**](https://sgfin.github.io/2019/06/19/Causal-Inference-Book-All-DAGs/) and [**Causal Inference Book Part I -- Glossary and Notes**](https://sgfin.github.io/2019/06/19/Causal-Inference-Book-Glossary-and-Notes/)|Put together by Sam Finlayson, this is a nice collated list of DAGs and concepts from Hernan and Robins textbook. The rest of the posts are quite good too, but I found these most useful.|
R coding of Statistical Rethinking [**First Edition**](https://bookdown.org/content/3890) and [**Second Edition**](https://bookdown.org/content/4857)|Coding of Richard McElreaths statistical Rethinkgin book using `brms` package in R. Its fantastic.|
 [**Hernan and Robins in R and/or stata exercises**](https://remlapmot.github.io/cibookex-r/)|Want to follow along with the book and avoid SAS, this is a resource for you!|

Blogs
---
Title and Author | Description and/or Extra Material
---|----
[**Zad Chow's Less Likey Blog**](https://lesslikely.com/)|Such great content here including my favorite, his S Value [post](https://lesslikely.com/statistics/s-values/) and [ S value calculator](https://data.lesslikely.com/s-values/)|
|[**Jonathan Bartlett The Stats Geek Blog**](http://thestatsgeek.com/)||
|[**Andrew Gelman's Blog**](https://statmodeling.stat.columbia.edu/)|Short, sweet, thought provoking posts.|
|[**Simply Statistics Blog**](https://simplystatistics.org/)|A statistics blog by Rafa Irizarry, Roger Peng, and Jeff Leek|
|[**R Bloggers**](https://www.r-bloggers.com/)|Great blog that highlights posts that cover new R packages, analysis methods, etc.|
|[**Frank Harrell's Blog Posts**](https://www.fharrell.com/post/)||
|[**Doing Bayesian Data Analysis**](http://doingbayesiandataanalysis.blogspot.com/)|Great blog but hasnt been updated in awhile|
[**Solomon Kurtz's Blog**](https://solomonkurz.netlify.app/blog/)| Fantastic blog, bayesian heavy. With R code works through different analyses.|
[**datamethods**](https://discourse.datamethods.org/)|Not really a blog, but a discussion board where epi/biostat issues are discussed. Really fantastic rabbit hole.|


Societies Worth Joining (i.e., I am a member of)
---
Name | Description
---|---
[**Society for Causal Inference**](https://sci-info.org/)|Relatively new society but worth joining to gain access to growing content|
[**Society for Epidemiologic Research(SER)**](https://epiresearch.org/)|Good organization for those interested in epi research, particularly if there is interest in methods|
[**American Statistical Association**](https://www.amstat.org)| Interested in statistics or biostat? This is self explanatory|


...more to come