---
title: "List of my favorite books"
author: "TF"
date: '2020-03-12'
output:
  html_document:
    df_print: paged
featured: yes
image:
  caption: ''
  focal_point: ''
  preview_only: no
lastmod: '2020-03-12T18:32:22-04:00'
categories: []
projects: []
slug: list-of-my-favorite-books
subtitle: ''
summary: This is a list of my favorite books across all categories
tags: []
authors: []
---
This is pretty self explanatory, but these are my fav books that Ive used throughout my education. I think they are spectacular resources for learning and in addition to sharing them with readers, it is nice to keep a list all in one place. What better place than on my web site?


## <u>Epidemiology & Biostat</u>

Title and Author | Description and/or Extra Material
-----|---
[Epidemiology: An Introduction](https://global.oup.com/academic/product/epidemiology-9780199754557?cc=ca&lang=en&) <br> by Ken Rothman|[Companion Site](https://global.oup.com/us/companion.websites/9780199754557/)|
|[Epidemiology By Design: A Causal Appoach to the Health Sciences](https://global.oup.com/academic/product/epidemiology-by-design-9780190665760?cc=us&lang=en&)<br>by Daniel Westreich|
|[Modern Epidmiology 3rd Ed](https://shop.lww.com/Modern-Epidemiology/p/9781451190052)<br>By Rothman, Greenland and Lash|The [First Edition](https://www.amazon.com/Modern-Epidemiology-Kenneth-J-Rothman/dp/0316757764) and [2nd Edition](https://books.google.ca/books/about/Modern_Epidemiology.html?id=cL3zwIFHB7cC&redir_esc=y) are also excellent!|
[What If, Causal Inference](https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/)<br>by Miguel Hernan and Jamie Robins|[PDF](https://cdn1.sph.harvard.edu/wp-content/uploads/sites/1268/2020/02/ci_hernanrobins_21feb20.pdf)|
|[Statistical Rethinking](https://xcelab.net/rm/statistical-rethinking/)<br>by Richard McElreath|
|[Probability](https://projects.iq.harvard.edu/stat110/home)<br>by Joseph Blitzstein and Jessica Hwang|Version 1 [PDF](http://dl.rasabourse.com/Harvard%20Statistics.pdf)<br>Version 2 [PDF](https://drive.google.com/file/d/1VmkAAGOYCTORq1wxSQqy255qLJjTNvBI/view)|
|[Regression Modeling Strategies](http://biostat.mc.vanderbilt.edu/wiki/Main/RmS)<br>by Frank Harrell|PDF [here](https://link.springer.com/content/pdf/10.1007%2F978-3-319-19425-7.pdf)|
|[Applied Longitudinal Data Analysis](https://content.sph.harvard.edu/fitzmaur/ala2e/)<br>by Fitzmaurice, Laird and Ware|
|[An Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)<br>by James, Witten, Hastie, And Tibshirani|[PDF](https://www.ime.unicamp.br/~dias/Intoduction%20to%20Statistical%20Learning.pdf) and [YouTube Videos](https://www.youtube.com/channel/UC4OWDcPB1peiBXDfCSZ3h-w)|
|[Doing Bayesian Data Analysis](https://sites.google.com/site/doingbayesiandataanalysis/)<br>by John Kruschke|[Whats new in the 2nd Ed.](https://sites.google.com/site/doingbayesiandataanalysis/what-s-new-in-2nd-ed)|
|[Explanation in Causal Inference](https://global.oup.com/academic/product/explanation-in-causal-inference-9780199325870?cc=us&lang=en&)|Great resource for causal analysis, although the book is really written for SAS users and not R users, unfortunately. [Companion Website here](https://global.oup.com/us/companion.websites/9780199325870/)|
|[Statistical Issues in Drug Development](https://www.wiley.com/en-us/Statistical+Issues+in+Drug+Development%2C+2nd+Edition-p-9780470018774)<br>by Stephen Senn|Excellent resource for learning about and understanding statistical issues in Clinical Trials and RCTs|


## <u>Medical</u>
Favorites from medical school and training. Included basic science books and might be a good reference for med students looking for **the best** references. Cince my focus is surgery and critical care you will get books slanting that way (eg, anatomy, physiology, pathophys, surgical)

Title and Author | Description and/or Extra Material
-----|---
[Medical Physiology](https://www.elsevier.com/books/medical-physiology/boron/978-1-4557-4377-3)<br>by Boron and Boulpaep|Wuite detailed covereage of physiology, useful for a deep dive.|
|[Best and Taylor's Physiologic Basis of Medical Practice](https://www.goodreads.com/book/show/26013382-best-taylors-physiological-basis-of-medical-practice)<br>by Tandon and Tripathi|I love the presentation of the information in this book. Also useful for a deep dive.|
|[Marino's The ICU Book](https://shop.lww.com/Marino-s-The-ICU-Book--Print---Ebook-with-Updates/p/9781451121186)<br> by Paul Marino|The ICU book for quick learning.|
|[West's Respiratory Physiology](https://shop.lww.com/West-s-Respiratory-Physiology/p/9781496310118)<br>by West|Wonderful [companion lectures at UCSD](https://meded.ucsd.edu/ifp/jwest/resp_phys/) to go with it|
|[West's Pulmonary Pathophysiology]()<br>by West|Wonderful [companion lectures at UCSD](https://meded.ucsd.edu/ifp/jwest/pulm_path/index.html)|
|[Gray's Anatomy: The Anatomical Basis of Clinical Practice](https://www.us.elsevierhealth.com/grays-anatomy-9780702052309.html)<br>By Standring |Quite in depth anatomy book way beyond just an atlas. Great reference particularly for a surgeon|
|[Anatomy: A Photographic Atlas](https://shop.lww.com/Anatomy/p/9781451193183) |Wonderful book that includes real dissection photographs|
|[Toronto Notes](https://uoftbookstore.com/shop_product_detail.asp?catalog_group_id=MTMxXFwgNjE&catalog_group_name=TWVkaWNhbFxcIE1lZGljYWwgUmVmZXJlbmNl&catalog_id=474&catalog_name=UmV2aWV3IE5vdGVz&pf_id=442184&product_name=VG9yb250byBOb3RlcyAyMDIwIChCb29rIE9ubHkp&type=3&target=shop_product_list.asp) |Fabulous summaries of medical information you will need|
|[First Aid for the Basic Sciences: General Principles](https://www.mhprofessional.com/9781259587016-usa-first-aid-for-the-basic-sciences-general-principles-third-edition-group)<br>and<br>[First Aid for the Bacis Sciences: Organ Systems](https://www.mhprofessional.com/9781259587030-usa-first-aid-for-the-basic-sciences-organ-systems-third-edition-group)|These are both wonderful resources to summarize the "first two years" of med school curriculum and should accompany study of lecture and material (imo)| 
|[Atlas of Human Anatomy ](https://www.elsevier.com/books/atlas-of-human-anatomy/netter/978-1-4557-0418-7)<br>by Frank Netter |Didnt appreciate how awesome this is until I was in surgery residency. Its a great reference|
|[Essentials of General Surgery](https://shop.lww.com/Essentials-of-General-Surgery-and-Surgical-Specialties/p/9781975107123)<br>by Lawrence|Excellent intro summary for medical students going into MS4 rotations|
|[Anatomy as a basis for clinical medicine](https://openlibrary.org/books/OL2225608M/Anatomy_as_a_basis_for_clinical_medicine)<br>by ECB Hall-Craggs|This is an out of print and not well known book, but have found it to be a great way to learn anatomy and a great reference too|
|[The Physiologic Basis of Surgery](https://shop.lww.com/Physiologic-Basis-of-Surgery/p/9780781771382)<br>By O'Leary|One of my favorite surgery textbooks|
|[Medical Microbiology](https://www.elsevier.com/books/medical-microbiology/murray/978-0-323-29956-5)<br>By Murray|The book I used in med school and quite useful for that purpose. The author, murray, was actually my lecturer|
|[Basic Immunology](https://www.elsevier.com/books/basic-immunology/abbas/978-0-323-54943-1)<br>By Abbas|The book I used in med school, much lighter than Janeways and hits all the pertinent points for physicians|

## <u>Popular Science and Math</u>

Title and Author | Description and/or Extra Material
-----|---
[The Simpsons and Their Mathematical Secrets](https://www.simonsingh.net/Simpsons_Mathematics/book/)<br>by Simon Singh||
|[We Have No Idea](http://phdcomics.com/noidea/)<br>by Jorge Cham and Daniel Whiteson||
|[The Rise and Fall of the Dinosaurs](https://www.harpercollins.com/9780062490421/the-rise-and-fall-of-the-dinosaurs/)<br>by Stephen Brusatte||
|[What If?: Serious Scientific Answers to Absurd Hypothetical Questions](https://what-if.xkcd.com/book/)<br>by Randall Munroe||
|[Academia Obscura](http://www.academiaobscura.com/book/)<br>by Glen Wright||

## <u>Fiction</u>

Title and Author | Description and/or Extra Material
-----|---
[Douglas Adams](https://douglasadams.com/) books in general<br>[The Hitchiker's Guide to the Galaxy](https://douglasadams.com/creations/hhgg.html)<br>[Dirk Gently Series](https://douglasadams.com/creations/dirk.html)| |
|[Terry Pratchett](https://www.terrypratchettbooks.com/books/) books in general, too<br>[Discworld Series](https://www.terrypratchettbooks.com/book-series/discworld/)<br>[Good Omens](https://www.terrypratchettbooks.com/books/good-omens/)||
|[The Dinosaur Feather](https://www.fantasticfiction.com/g/sissel-jo-gazan/dinosaur-feather.htm)<br>and<br>[The Arc of the Swallow](https://www.fantasticfiction.com/g/sissel-jo-gazan/arc-of-the-swallow.htm)|Thrillers set in the world of academia, whats not to love?|
|

## <u>Mathematics</u>
Title and Author | Description and/or Extra Material
-----|---
[Calculus 9th ed.](https://www.pearson.com/us/higher-education/product/Thomas-Calculus-9th-Edition/9780201531749.html)<br>By Thomas and Finney|Wonderfully lucid exposition of calculus|
|[Intro. to Linear Algebra](https://math.mit.edu/~gs/linearalgebra/)<br>by Gilbert Strang|Might be best paired with the [MIT OCW Course](https://ocw.mit.edu/courses/mathematics/18-06-linear-algebra-spring-2010/)|
|[Calculus](https://www.maa.org/press/maa-reviews/calculus-4)<br>by Spivak||
|

## <u>Physics</u>
Title and Author | Description and/or Extra Material
-----|---
[Feynman's Lectures on Physics](https://www.feynmanlectures.caltech.edu/info/)|Online Version of the books [here](https://www.feynmanlectures.caltech.edu/)|
|[University Physics with Modern Physics](https://www.pearson.com/store/p/university-physics-with-modern-physics/P100002510958/9780135159705)<br>by Young and Freedman|Calculus based physics|
|[Physics, Volume 1, 5th Edition](https://www.wiley.com/en-us/Physics%2C+Volume+1%2C+5th+Edition-p-9780471320579)<br>and<br>[Physics, Volume 2, 5th Edition](https://www.wiley.com/en-us/Physics%2C+Volume+2%2C+5th+Edition-p-9780471401940)<br>by Resnick Halliday and Krane|Two parter but also great|


## <u>Chemistry</u>
Title and Author | Description and/or Extra Material
-----|---
[Biochemistry](https://www.pearson.com/us/higher-education/program/Mathews-Biochemistry-4th-Edition/PGM39253.html)<br>by Matthews and Van holde|Best Intro Biochem book, and better than Lehninger IMO|
|[Biochemistry](https://www.wiley.com/en-us/Biochemistry%2C+4th+Edition-p-9780470570951)<br>by Voet and Voet|The tome; side note: I got to meet Drs. Voet and Voet and have my 3rd Ed signed|
|[Organic Chemistry](https://www.macmillanlearning.com/college/us/product/Organic-Chemistry/p/1936221349)<br>by Marc Loudon|Better than McMurray and Fay in my opinion. There great great corresponding review sheets [here](https://orgchemboulder.com/Lectures/Reviews/Reviews.shtml)|
|[Chemical Principles: The Quest for Insight](https://www.macmillanlearning.com/college/us/product/Chemical-Principles/p/1464183953)<br>by Atkins Jones and Laverman<br>or<br>[Principles of Modern Chemistry](https://www.cengage.com/c/principles-of-modern-chemistry-8e-oxtoby/9781305079113PF/) by Oxtoby| Both are great resources for gen chem learning with calculus base in the kinetics and energetics sections|
|[Inorganic Chemistry](https://www.pearson.com/us/higher-education/program/Miessler-Inorganic-Chemistry-5th-Edition/PGM75285.html)<br>by Miessler and Tarr||
|

## <u>Biology</u>
Title and Author | Description and/or Extra Material
-----|---
[Campbell Biology](https://www.pearson.com/us/higher-education/program/Urry-Campbell-Biology-Plus-Mastering-Biology-with-Pearson-e-Text-Access-Card-Package-11th-Edition/PGM209351.html)|What can be said about this? Comprehenseive intro level biology text covering the entirety of the field from 1000ft view|
|[Molecular Biology of the Cell](https://www.ncbi.nlm.nih.gov/books/NBK21054/)<br>by Bruce Alberts|I used the 4th ed. (linked) but Im sure the [5th]() & [6th](https://www.crcpress.com/Molecular-Biology-of-the-Cell/Alberts/p/book/9781315735368) eds. are great too!|
|[Physical Biology of the Cell](https://www.crcpress.com/Physical-Biology-of-the-Cell/Phillips-Kondev-Theriot-Garcia-Phillips-Kondev-Theriot-Garcia/p/book/9780815344506)<br>by Philips <i>et al.<i>||
|[Molecular Cell Biology](https://www.macmillanlearning.com/college/us/product/Molecular-Cell-Biology/p/1464183392)<br>by Lodish and Baltimore||
|[Karp's Cell and Molecular Biology: Concepts and Experiments](https://www.wiley.com/en-us/Karp%27s+Cell+and+Molecular+Biology%3A+Concepts+and+Experiments%2C+8th+Edition-p-9781118886144)|I used this as my into cell bio book and loved it; was a great intro book.|
|[Janeway's Immunobiology](https://wwnorton.com/books/9780815345053)<br>By Murphy and Weaver|Research Immunology text, too much depth for medical school more for adv undergrad or grad school|
|[Brock Book of Microorganisms](https://www.pearson.com/store/p/brock-biology-of-microorganisms/P100000185862/9780134261928)|Great intro to microbiology text|
|

    
...more to come
