---
title: "Some of my favorite resources"
author: "TF"
date: '2020-03-12'
categories: []
featured: yes
image:
  caption: ''
  focal_point: ''
  preview_only: no
lastmod: '2020-03-12T10:18:12-04:00'
projects: []
slug: some-of-my-favorite-resources
subtitle: ''
summary: My favorite resources for learning and fun from across the internet
tags: []
authors: []
header-includes:
   - \usepackage{marvosym}
---

The internet has a plethora of resources to learn more about science, math, and other interests. I decided to collate all my favorite sites and posts.


## [**Statistical Rethinking**](https://xcelab.net/rm/)

Richard McElreath's [Statistical Rethinking](https://www.crcpress.com/Statistical-Rethinking-A-Bayesian-Course-with-Examples-in-R-and-STAN/McElreath/p/book/9780367139919) book is famous (at least is seems to be). Its fantastic for both learning statistical thinking, but also learning bayesian analysis from the ground up. The most wonderful part of it, for those of use who havent taken multivariate calculus, is that he teaches without requring it. It also comes paired with a [wonderful lecture video series provided for free](https://www.youtube.com/channel/UCNJK6_DZvcMqNSzQdEkzvzA).

You can also follow him on twitter [$@$rlmcelreath](https://twitter.com/rlmcelreath)

## **Solomon Kurz's R coding**
```{r, echo=FALSE}
blogdown::shortcode('tweet', '1220358159593766913')
```

Solomon's main page is [here](https://solomonkurz.netlify.com/) and he offers many great things. If you go to the [book length projects](https://solomonkurz.netlify.com/bookdown/) site you will see that there are many great reanalysis "books" where Solomon uses tidyverse and ggplot to complete aompanion analysis for [John Kruschke's Doing Bayesian Data Analysis](https://bookdown.org/content/3686/), [Andrew Hayes' Introduction to Mediation, Moderation, and Conditional Process Analysis](https://bookdown.org/ajkurz/recoding_Hayes_2018/), and of course last but not least the most popular reanalysis, that of [Richard McElreath's (see above) Statistical Rethinking](https://bookdown.org/content/3890/).

Solomon also has a great blog with posts like [Make model diagrams, Kruschke style](https://solomonkurz.netlify.com/post/make-model-diagrams-kruschke-style/)

You can also follow him on twitter [$@$SolomonKurz](https://twitter.com/SolomonKurz)

## [**Causal Inference Book**](https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/)

How could I ignore this resource--I would need to be daft to! I used this book by Robins and Hernan  extensively during both my intro epi course and my casual inference course while completing my MPH (luckily Hernan was my causal inference instructor). The link to the webpage is [here](https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/) and includes a link to the [free pdf](https://cdn1.sph.harvard.edu/wp-content/uploads/sites/1268/2020/02/ci_hernanrobins_21feb20.pdf) and code for SAS, Stata, and R.

There is also a nicely done [bookdown project](https://causalinferencebookr.netlify.com/) by [Malcolm Barrett](https://malco.io/) that works through the coding for the book and is a wonderful companion.

## [**R Psychologist**](https://rpsychologist.com/)

Wonderful [visualizations](https://rpsychologist.com/tag/visualization)

## [**Sam Finlayson's Site**](https://sgfin.github.io/)

[DAGs](https://sgfin.github.io/2019/06/19/Causal-Inference-Book-All-DAGs/)

[Causal Inference Notes](https://sgfin.github.io/2019/06/19/Causal-Inference-Book-Glossary-and-Notes/)

## [**Stat 110 Probability by Joseph Blitzstein**](https://projects.iq.harvard.edu/stat110)
This is an amazing first course covering probability. Not only does it link to his [amazing youtube videos](https://www.youtube.com/playlist?list=PL2SOU6wwxB0uwwH80KTQ6ht66KWxbzTIo), [handouts](https://projects.iq.harvard.edu/stat110/handouts), [practice problems and solutions](https://projects.iq.harvard.edu/stat110/strategic-practice-problems), a free copy of [his book](http://probabilitybook.net/), but it also has the added content from his EdX course. Joe is an amazing resource and I cant recommend all this enough.

You can also follow him on twitter
[$@$stat110](https://twitter.com/stat110)

## [**Darren Dahly's (EH6124) Clinical Trial Design and Analysis course videos**](https://www.youtube.com/watch?v=dnfXsqwTrE0&list=PL1TlcXRy7yCsRWza4xtKoir2KEvYcYkHz)
This is a fantastic set of videos introducing the theroy and practice of clinical trials. You can also follow Darren on twitter for added value: [$@$statsepi](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjytJH5_8noAhVpj3IEHbu3ApUQ6F56BAgBEAI&url=https%3A%2F%2Ftwitter.com%2Fstatsepi%3Fref_src%3Dtwsrc%255Egoogle%257Ctwcamp%255Eserp%257Ctwgr%255Eauthor&usg=AOvVaw1mxCaF3VMVv5BF3oq46Q5J)

## [**Petersen and Balzer's Causal Inference Site**](https://www.ucbbiostat.com/)

## [**Noam Ross' GAMs in R tutorial**](https://noamross.github.io/gams-in-r-course/)

## [**Frank Harrell's Discourse site: Datamethods**](https://discourse.datamethods.org/)
(requires login)

## [**Frank Harrell's Biostatistics Resources**](https://www.fharrell.com/)

[Regression Modeling Strategies](http://hbiostat.org/doc/rms.pdf)

[Biostatistics for Biomedical Research](http://hbiostat.org/doc/bbr.pdf)

## [**MIT Open Courseware**](https://ocw.mit.edu/index.htm)

## [**Khan Academy**](https://www.khanacademy.org/)
[Youtube site here](https://www.youtube.com/user/khanacademy)

## [**3Blue1Brown Youtube Videos**](https://www.youtube.com/channel/UCYO_jab_esuFRV4b17AJtAw)
Site descirption: 3blue1brown, by Grant Sanderson, is some combination of math and entertainment, depending on your disposition. The goal is for explanations to be driven by animations and for difficult problems to be made simple with changes in perspective. 

## [**StatQuest by Josh Starmer**](https://www.youtube.com/channel/UCtYLUTtgS3k1Fg4y5tAhLbw)

## [**Vanderbilt Biostatistics Resources**](http://biostat.mc.vanderbilt.edu/wiki/)

## [**Stats Notes in the BMJ**](https://www-users.york.ac.uk/~mb55/pubs/pbstnote.htm)
Wonderful list of papers in the BMJ that were written by Doug Altman and Martin Bland.

## [**Jama Guide to Stats and Medicine**](https://jamanetwork.com/collections/44042/guide-to-statistics-and-medicine)
*this isnt free, but it quite a good resource particularly is you have institutional or personal JAMA access.

## [**Univ. of Bristol Online Multilevel Modeling Site**](http://www.bristol.ac.uk/cmm/) 
The [Online course is here](https://www.bristol.ac.uk/cmm/learning/online-course/) The course requires free registration but is absolutely fantastic for learning multilevel modeling.

## **Directed Acyclic Graph (DAG) Resources:**
Stuff to help you learn DAGs.

Title | Description
---|---
[Ellie Murray's DAGs in LaTex](https://github.com/eleanormurray/causalgraphs_latex)||
|[Maria Glymour's Paper on DAGs](/files/glymourdags.pdf)||
|[Malcom Barrett's DAGTEX](https://github.com/malcolmbarrett/dagtex)<br>and<br> [GGDAG](https://ggdag.malco.io/) packages||
|[Miguel Hernan's Causal Diagrams: Draw You Assumptions Before Your Conclusions Course](https://online-learning.harvard.edu/course/causal-diagrams-draw-your-assumptions-your-conclusions)|(note this is on EdX and requires signing up, which is free)|
|

## **R Resources**
Stuff to help you learn R, the greatest statistical "package."

Title | Description
---|---
[R for Data Science](https://r4ds.had.co.nz/)<br>by Wickham and Grolemund|Free online book by Hadley, not much else to say|
|[Stat 454](https://stat545.com/)<br>by Jenny Bryan|Prime intro to using R for data analysis|
|[Introduction to Data Science Data Analysis and Prediction Algorithms with R](https://rafalab.github.io/dsbook/)<br>by Rafael Irizarry||
|[Applied Statistics with R](https://daviddalpiaz.github.io/appliedstats/)| [PDF Version](http://daviddalpiaz.github.io/appliedstats/applied_statistics.pdf) for local use|
|[RMarkdown intro](https://ourcodingclub.github.io/tutorials/rmarkdown/)||
|[RBasics Tutorial](https://r-statistics.co/R-Tutorial.html)||
|Xaringan Tutorials [here](https://apreshill.github.io/data-vis-labs-2018/slides/06-slides_xaringan.html#64), [here](https://arm.rbind.io/slides/xaringan.html#16) and [here](https://xaringantutorial.netlify.com/#1)|These are great sources to get started using Xaringan for making slide presentations in R|


## **Git Resources**
Stuff to help you learn git, which is something I didn't find easy.

Title | Description
---|---
[An Intro to Git and GitHub for Beginners (Tutorial)](https://product.hubspot.com/blog/git-and-github-tutorial-for-beginners)<br> by Meghan Nelson|Great intro tutorial that walks you through basics of using Git|
|[List of Git Commands](https://git-scm.com/docs)|Reference for all Git Commands|
|[Git Visual Cheatsheet](https://ndpsoftware.com/git-cheatsheet.html#loc=workspace;)|Visual refence to help understand  the git commands|
|[Git cheatsheet](https://education.github.com/git-cheat-sheet-education.pdf)|Classic cheatsheet of commands|

## **Bash Resources**
Stuff to help you learn BASH, which is something I also didn't find easy.

Title | Description
---|---
[BASH intro video](https://www.youtube.com/watch?v=oxuRxtrO2Ag)||
|[Regex tutorial](https://www.regular-expressions.info/tutorial.html)|tutorials in how to use regular expressions|

## **$\LaTeX$ Resources**
Stuff to help you learn $\LaTeX$, which can be quite a slog at times.

Title | Description
---|---
[Comprehensive Symbol Sheet](http://tug.ctan.org/info/symbols/comprehensive/symbols-a4.pdf)||


...More to come.